const config = {
    totalResults: 2,
    itemsPerPage: 1000,
    startIndex: 0,
    schemas: ["urn:ietf:params:scim:api:messages:2.0:ListResponse"],
    Resources: [
        {
            id: "urn:ietf:params:scim:schemas:core:2.0:User",
            name: "User",
            endpoint: "/Users",
            description: "SCIM core resource for representing users",
            attributes: [
                {
                    name: "id",
                    type: "string",
                    multiValued: false,
                    description: "Unique identifier for the SCIM resource",
                    mutability: "readOnly",
                    required: false,
                    caseExact: false,
                },
                {
                    name: "userName",
                    type: "string",
                    multiValued: false,
                    description: "Unique identifier for the User",
                    mutability: "readOnly",
                    required: true,
                    caseExact: false,
                },
                {
                    name: "name",
                    type: "complex",
                    multiValued: false,
                    description: "The components of the Users real name",
                    mutability: "readWrite",
                    required: false,
                    caseExact: false,
                    subAttributes: [
                        {
                            name: "formatted",
                            type: "string",
                            description: "The full name formatted for display",
                            mutability: "readOnly",
                            required: false,
                            caseExact: false,
                        },
                    ],
                },
                {
                    name: "active",
                    type: "boolean",
                    multiValued: false,
                    description: "A Boolean value indicating the Users status",
                    mutability: "readWrite",
                    required: false,
                    caseExact: false,
                },
                {
                    name: "language",
                    type: "string",
                    multiValued: false,
                    description: "Value indicating users ISO Language key",
                    mutability: "readWrite",
                    required: true,
                    caseExact: false,
                },
                {
                    name: "idpSource",
                    type: "string",
                    multiValued: false,
                    description: "Value indicating the IDP source",
                    mutability: "readOnly",
                    required: true,
                    caseExact: false,
                    canonicalValues: [
                        { value: "azure-bearer" },
                        { value: "ldap" },
                        { value: "saml" },
                        { value: "local" },
                        { value: "jwt" },
                        { value: "external" },
                        { value: "oauth2" },
                        { value: "openid-connect" },
                        { value: "sap" },
                    ],
                },
                {
                    name: "emails",
                    type: "complex",
                    multiValued: true,
                    description: "email address for the User",
                    mutability: "readWrite",
                    required: true,
                    caseExact: false,
                    subAttributes: [
                        {
                            name: "value",
                            type: "string",
                            description: "The value",
                            mutability: "readWrite",
                            required: false,
                            caseExact: false,
                        },
                        {
                            name: "primary",
                            type: "boolean",
                            description: "Is the primary value",
                            mutability: "readOnly",
                            required: false,
                            caseExact: false,
                        },
                        {
                            name: "display",
                            type: "string",
                            description: "The value suitable for display",
                            mutability: "readWrite",
                            required: false,
                            caseExact: false,
                        },
                        {
                            name: "type",
                            type: "string",
                            description: "A label indicating the attributes function",
                            mutability: "readWrite",
                            required: false,
                            caseExact: false,
                            canonicalValues: [{ value: "work" }],
                        },
                    ],
                },
                {
                    name: "phoneNumbers",
                    type: "complex",
                    multiValued: true,
                    description: "Phone numbers for the User",
                    mutability: "readWrite",
                    required: false,
                    caseExact: false,
                    subAttributes: [
                        {
                            name: "value",
                            type: "string",
                            description: "The value",
                            mutability: "readWrite",
                            required: false,
                            caseExact: false,
                        },
                        {
                            name: "type",
                            type: "string",
                            description: "A label indicating the attributes function",
                            mutability: "readWrite",
                            required: false,
                            caseExact: false,
                            canonicalValues: [{ value: "work" }, { value: "mobile" }],
                        },
                    ],
                },
                {
                    name: "groups",
                    type: "complex",
                    multiValued: true,
                    description: "The groups a user belongs to",
                    mutability: "readOnly",
                    required: true,
                    subAttributes: [
                        {
                            name: "value",
                            type: "string",
                            description: "The id of the group",
                            mutability: "readOnly",
                            required: false,
                            caseExact: false,
                        },
                        {
                            name: "display",
                            type: "string",
                            description: "The name of the group",
                            mutability: "readWrite",
                            required: false,
                            caseExact: false,
                        },
                    ],
                },
            ],
        },
        {
            id: "urn:ietf:params:scim:schemas:core:2.0:Group",
            name: "Group",
            description: "SCIM core resource for representing groups",
            schema: "urn:ietf:params:scim:schemas:core:2.0:Group",
            endpoint: "/Groups",
            attributes: [
                {
                    name: "id",
                    type: "string",
                    multiValued: false,
                    description: "Unique identifier for the SCIM resource.",
                    mutability: "readOnly",
                    required: true,
                    caseExact: false,
                },
                {
                    name: "displayName",
                    type: "string",
                    multiValued: false,
                    description: "The name of the Group, suitable for display",
                    mutability: "readWrite",
                    required: false,
                    caseExact: false,
                },
                {
                    name: "members",
                    type: "complex",
                    multiValued: true,
                    description: "The members of the group",
                    mutability: "readWrite",
                    required: false,
                    subAttributes: [
                        {
                            name: "value",
                            type: "string",
                            description: "The id of the member in the group",
                            mutability: "readWrite",
                            required: false,
                            caseExact: false,
                        },
                        {
                            name: "display",
                            type: "string",
                            description: "The name of the member in the group",
                            mutability: "readOnly",
                            required: true,
                            caseExact: false,
                        },
                    ],
                },
            ],
        },
    ],
};

result.data = config;
complete();
